elastic-prompt-search/config/routes.rb
Rails.application.routes.draw do
  # Route for searching prompts
  # Map GET requests to "/search/prompt" to "PromptsController#index" action
  get "/search/prompt", to: "prompts#index"

  root "prompts#index"
end

elastic-prompt-search/app/models/application_record.rb
# Define a Ruby on Rails base class named ApplicationRecord, inheriting from ActiveRecord::Base
class ApplicationRecord < ActiveRecord::Base
  # Designate this class as a primary abstract class
  primary_abstract_class
end

elastic-prompt-search/app/models/audit_log.rb
# Define a Ruby on Rails model named AuditLog, inheriting from ApplicationRecord
class AuditLog < ApplicationRecord
    # Validate uniqueness of the search_term attribute
    validates :search_term, uniqueness: true
  end
  

elastic-prompt-search/app/models/prompt.rb
# Import the Elasticsearch Model module for integrating Elasticsearch with the model
require 'elasticsearch/model'

# Define a Ruby on Rails model named Prompt, inheriting from ApplicationRecord
class Prompt < ApplicationRecord
  # Include Elasticsearch::Model module to enable Elasticsearch integration
  include Elasticsearch::Model

  # Include Elasticsearch::Model::Callbacks to enable callbacks for Elasticsearch actions
  include Elasticsearch::Model::Callbacks
end

elastic-prompt-search/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

elastic-prompt-search/app/controllers/prompts_controller.rb
require 'json'

class PromptsController < ApplicationController

  # GET /prompts/1 or /prompts/1.json
  def index
    # Get search query from URL parameters
    query = params[:query]

    # If query is provided, search Elasticsearch
    if query.present?
      # Perform search using Elasticsearch's search method with params
      prompts = Prompt.__elasticsearch__.search(query).response

      # Parse response JSON and extract content from hits
      parsed_json = JSON.parse(prompts.to_json)
      @prompts = parsed_json['hits']['hits'].map { |hit| hit['_source']['content'] }

      # Create audit log if prompts found
      if @prompts.present?
        @audit_log = AuditLog.new(search_term: query, content: @prompts)
        @audit_log.save
      end
    end
  end
end

elastic-prompt-search/app/helpers/application_helper.rb
module ApplicationHelper
end

elastic-prompt-search/app/helpers/audit_logs_helper.rb
module AuditLogsHelper
end

elastic-prompt-search/app/helpers/prompts_helper.rb
module PromptsHelper
end

elastic-prompt-search/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Audemic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

elastic-prompt-search/app/views/prompts/index.html.erb
<p style="color: green"><%= notice %></p>
 
 <div class="container">
  <h1>Search Prompts</h1>
  <%= form_tag(search_prompt_path, method: :get) do %>
    <%= text_field_tag(:query, params[:query], placeholder: 'Enter your search query') %>
    <%= submit_tag('Search') %>
  <% end %>
 
  <% if @prompts.present? %>
    <h2>Search Results:</h2>
    <ul>
      <% @prompts.each do |prompt| %>
        <li><%= prompt %></li>
      <% end %>
    </ul>
  <% else %>
    <p>No results found.</p>
  <% end %>
</div>